name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node-version:
          - 18
        architecture:
          - x64
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ${{ matrix.architecture }}
          cache: "yarn"
      - name: Install Dependencies
        run: |
          npm install @sudoo/build-cli -g
          sudoo-build install
      - name: Lint
        run: |
          sudoo-build --type typescript-react lint
      - name: Test
        run: |
          sudoo-build --type typescript-react coverage
      - name: Build
        run: |
          yarn run build
      - name: Codecov
        uses: codecov/codecov-action@v1
